#!/bin/bash

PS3='コマンド? '

select cmd in up down left right look quit
do
  case $cmd in
  up)
    echo '上に移動しました';;
  down)
    echo '下に移動しました';;
  left)
    echo '左に移動しました';;
  right)
    echo '右に移動しました';;
  look)
    echo 'アイテムが落ちています';;
  quit)
    echo '終了します'
    break;;
  *)
    echo "$REPLY"'というコマンドはありません';;
  esac
  echo
done
